name: Debricked Vulnerable Functionality for Java (generic)
author: Debricked
description: todo
inputs:
  path-to-compiled-files:
    description: Comma separated list of folders containing compiled files of the project (your code)
    required: true
  path-to-library-files:
    description: Comma separated list of folders containing jars of all dependencies used (library code)
    required: true
runs:
  using: docker
  image: docker://debricked/vulnerable-functionality-java:version-5
  entrypoint: /vulnfunc/java/github-action.sh
  args:
    - ${{ inputs.path-to-compiled-files }}
    - ${{ inputs.path-to-library-files }}
branding:
  color: purple
  icon: filter
