name: Golang test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Set up Go 1.16.5
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.5'
      - name: Display Golang version
        run: go version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          go get -u golang.org/x/tools/cmd/callgraph
          cd golang/test && go install
      - name: Test with pytest
        run: |
          pip install pytest
          pytest golang/test/go_cg_test.py
