name: JavaScript test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r javascript/src/requirements.txt
          sudo npm install -g @persper/js-callgraph
          sudo apt-get install dos2unix
      - name: Test with pytest
        run: |
          pip install pytest
          pytest 
