name: Vulnerable Functionality Maven

on: [push]

jobs:
  vulnfunc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ./java/maven
      with:
        root-pom-directory: 'java/common'
