name: Vulnerable Functionality Generic

on: [push]

jobs:
  vulnfunc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - run: mvn -B -f java/common package dependency:copy-dependencies -DoutputDirectory=dependencies -DskipTests
    - uses: ./java
      with:
        path-to-compiled-files: 'java/common/target/classes/'
        path-to-library-files: 'java/common/dependencies'
